# Generated by Django 5.2.5 on 2025-08-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_set_setnumber_workout_name_alter_set_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='set',
            name='setNumber',
        ),
    ]
